// Categorías de palabras cubanas para el juego del impostor

// Jerga y expresiones cubanas
export const JERGA_CUBANA = [
  'asere',
  'acere',
  'pinga',
  'reparto',
  'yuma',
  'fula',
  'chavito',
  'guagua',
  'botero',
  'almendron',
  'jama',
  'timba',
  'guarapo',
  'tremendo',
  'candela',
  'bemba',
  'chama',
  'chamo',
  'comemierda',
  'singao',
  'descarga',
  'guarapera',
  'jinetero',
  'jinetera',
  'paladar',
  'bodega',
  'cola',
  'chopin',
  'pulover',
  'blumer',
  'sayuela',
  'chancleta',
  'tenis',
  'moña',
  'puro',
  'tabaco',
  'mojito',
  'daiquiri',
  'malecon',
  'guajiro',
  'mulata',
  'negron',
  'blanquito',
  'socio',
  'consorte',
  'monina',
  'ecobio',
  'baro',
  'pasta',
  'pincha',
  'chivato',
  'chivatear',
  'fiana',
  'talla',
  'chucho',
  'friki',
  'repa',
  'mikki',
  'bisne',
  'resolver',
  'luchar',
  'inventar',
  'escapar',
  'templar',
  'singadera',
  'bola',
  'tremenda',
  'arrancao',
  'pelao',
  'duro',
  'quedao',
  'volao',
  'fao',
  'fiao',
  'guanikiki',
  'papeao',
  'tragao',
  'empingao',
  'aplatanao',
  'despelote',
  'desbarajuste',
  'relajo',
  'chusmeria',
  'chusma',
  'fosforera',
  'yaguara',
  'jamonero',
  'picuo',
  'picua',
  'gusano',
  'comunista',
  'compañero',
  'revolucion',
  'libreta',
  'dieta',
  'mandao',
  'picadera',
  'merienda',
  'desayuno',
  'comida',
  'puntico',
  'derecho',
  'izquierda',
  'coger',
  'botar',
  'tumbar',
  'fletar',
  'cotorra',
  'ñoño',
  'punto',
  'quimbara',
  'bacalao',
  'croqueta',
  'bonche',
  'muela',
  'cuentero',
  'guaperia',
  'guapo',
  'fajao',
  'fajarse',
  'paquete',
  'carne de puerco',
];

// Influencers y figuras cubanas
export const INFLUENCERS_CUBANOS = [
  'otaola',
  'carlucho',
  'descemer',
  'gente de zona',
  'orishas',
  'cimafunk',
  'el chacal',
  'el micha',
  'chocolate mc',
  'leoni torres',
  'buena fe',
  'los van van',
  'habana de primera',
  'havana d primera',
  'el taiger',
  'yomil',
  'el dany',
  'jacob forever',
  'el chulo',
  'la diosa',
  'srta dayana',
  'divan',
  'baby lores',
  'insurrecto',
  'osmani garcia',
  'el principe',
  'los 4',
  'charanga habanera',
  'manolito simonet',
  'issac delgado',
  'paulito fg',
  'david calzado',
  'la elite',
  'wampi',
  'kimiko',
  'yordy',
  'el negrito',
  'el kokito',
  'manu manu',
  'el uniko',
  'yulien oviedo',
  'el kamel',
  'alex duvall',
  'el deny',
  'dj unic',
  'el brujo',
  'yakarta',
  'maykel osorbo',
  'el funky',
  'luis manuel otero',
  'yotuel',
  'beatriz luengo',
  'willy chirino',
  'gloria estefan',
  'celia cruz',
  'pitbull',
  'camila cabello',
  'william levy',
  'ana de armas',
  'daisy fuentes',
  'andy vazquez',
  'facundo correcto',
  'limay blanco',
  'alexis valdes',
  'carlos otero',
  'yunior morales',
  'cuqui la mora',
  'maikel pons',
  'osvaldo doimeadios',
  'luis silva',
  'pánfilo',
  'chequera',
  'eddy k',
  'gilberto santa rosa',
  'la india',
  'marc anthony',
  'alexander abreu',
  'haila',
  'osdalgia',
  'kelvis ochoa',
  'david torrens',
  'frank delgado',
  'polito ibañez',
  'silvio rodriguez',
  'pablo milanes',
  'carlos varela',
  'amaury gutierrez',
  'willy gonzalez',
  'el tosco',
  'tirso duarte',
  'tanya',
  'la charanga forever',
  'bamboleo',
  'azucar negra',
  'klimax',
  'manolin el medico',
  'ng la banda',
  'adalberto alvarez',
  'los aldeanos',
  'silvito el libre',
  'telmary',
  'x alfonso',
  'interactivo',
  'david blanco',
  'aldo moya',
];

// Comida cubana
export const COMIDA_CUBANA = [
  'moros',
  'congri',
  'yuca',
  'platano',
  'chicharron',
  'lechon',
  'ropa vieja',
  'vaca frita',
  'picadillo',
  'bistec',
  'fricasé',
  'potaje',
  'ajiaco',
  'caldosa',
  'tamal',
  'croqueta',
  'papa rellena',
  'empanada',
  'mariquita',
  'tostones',
  'fufu',
  'chatino',
  'boniatillo',
  'casquitos',
  'mermelada',
  'natilla',
  'arroz con leche',
  'flan',
  'churro',
  'cake',
  'pan con lechon',
  'medianoche',
  'sandwich cubano',
  'bocadito',
  'cangrejito',
  'perro caliente',
  'pizza cubana',
  'espagueti',
  'macarrones',
  'arroz frito',
  'chop suey',
  'pollo frito',
  'masas de cerdo',
  'higado',
  'lengua',
  'rabo encendido',
  'frijoles negros',
  'frijoles colorados',
  'arroz blanco',
  'arroz amarillo',
  'ensalada',
  'aguacate',
  'tomate',
  'pepino',
  'col',
  'boniato',
  'malanga',
  'calabaza',
  'quimbombo',
  'chayote',
  'name',
  'pan con tortilla',
  'pan con jamon',
  'pan con queso',
  'carne de res',
  'carne de cerdo',
  'pollo asado',
  'pescado frito',
  'camarones',
  'langosta',
  'enchilado',
  'cangrejo',
  'pulpo',
  'calamar',
  'tasajo',
  'bacalao a la vizcaina',
  'sopa de pollo',
  'caldo gallego',
  'fabada',
  'cocido',
  'arroz con pollo',
  'arroz con mariscos',
  'paella',
  'mofongo',
  'masreal',
  'chilindrón',
  'aporreado',
  'boliche',
  'carne con papa',
  'guiso',
  'estofado',
  'albondigas',
  'milanesa',
  'escalope',
  'cordon bleu',
  'lasaña',
  'canelones',
  'ravioles',
  'tortilla española',
  'revoltillo',
  'huevos fritos',
  'jamon serrano',
  'chorizo',
  'morcilla',
  'butifarras',
  'tamales en cazuela',
  'harina con cangrejo',
  'dulce de coco',
  'coco rallado',
  'turrón',
  'mazapán',
  'buñuelos',
  'torrijas',
  'panetela',
  'brazo gitano',
  'tres leches',
  'pudin',
  'gelatina',
  'batido',
  'jugo natural',
  'guarapo',
  'pru',
  'malta',
  'refresco',
  'cerveza',
  'ron',
  'cristal',
  'bucanero',
  'havana club',
  'santiago',
];

// Lugares y barrios de Cuba
export const LUGARES_CUBANOS = [
  'habana vieja',
  'vedado',
  'miramar',
  'centro habana',
  'cerro',
  'diez de octubre',
  'marianao',
  'playa',
  'la lisa',
  'guanabacoa',
  'regla',
  'alamar',
  'cojimar',
  'santa maria',
  'varadero',
  'cayo coco',
  'trinidad',
  'santiago',
  'holguin',
  'camaguey',
  'cienfuegos',
  'pinar del rio',
  'matanzas',
  'villa clara',
  'sancti spiritus',
  'ciego de avila',
  'las tunas',
  'granma',
  'guantanamo',
  'isla de la juventud',
  'coppelia',
  'la rampa',
  '23 y 12',
  'g y 23',
  'la piragua',
  'el rapido',
  'la tropical',
  'karl marx',
  'la madriguera',
  'fabrica de arte',
  'capitolio',
  'morro',
  'la cabaña',
  'plaza de la revolucion',
  'jose marti',
  'parque central',
  'prado',
  'neptuno',
  'san rafael',
  'galiano',
  'obispo',
  'cathedral',
  'floridita',
  'bodeguita del medio',
  'tropicana',
  'parisien',
  'cabaret nacional',
  'teatro nacional',
  'gran teatro',
  'museo de bellas artes',
  'museo de la revolucion',
  'plaza vieja',
  'plaza de armas',
  'san lazaro',
  'universidad',
  'colina',
  'infanta',
  'carlos tercero',
  'cuatro caminos',
  'monte',
  'reina',
  'belascoain',
  'zanja',
  'linea',
  'paseo',
  'primera',
  'tercera',
  'quinta avenida',
  'siboney',
  'atabey',
  'la coronela',
  'fontanar',
  'nautico',
  'biltmore',
  'santa fe',
  'jaimanitas',
  'baracoa',
  'el salado',
  'guines',
  'san antonio',
  'artemisa',
  'bahia honda',
  'viñales',
  'soroa',
  'las terrazas',
  'cayo largo',
  'cayo santa maria',
  'jardines del rey',
  'baconao',
  'el cobre',
  'bayamo',
  'manzanillo',
  'nuevitas',
  'moron',
  'jatibonico',
  'santa lucia',
  'guardalavaca',
  'playa esmeralda',
];

// Cosas típicas cubanas
export const COSAS_CUBANAS = [
  'domino',
  'bicicleta',
  'carretilla',
  'chivichana',
  'patineta',
  'pelota',
  'manilla',
  'collares',
  'santeria',
  'oricha',
  'babalawo',
  'changó',
  'yemayá',
  'ochún',
  'obatalá',
  'elegguá',
  'reggaeton',
  'timba',
  'salsa',
  'son',
  'rumba',
  'casino',
  'rueda de casino',
  'comparsa',
  'conga',
  'carnaval',
  'quince',
  'cumpleaños',
  'fiesta',
  'parranda',
  'despelote',
  'bembé',
  'toque',
  'ceremonia',
  'misa',
  'velorio',
  'guateque',
  'pachanga',
  'gozadera',
  'cha cha cha',
  'mambo',
  'bolero',
  'guaguancó',
  'columbia',
  'yambú',
  'clave',
  'bongo',
  'tumbadora',
  'tres',
  'güiro',
  'maracas',
  'trompeta',
  'piano',
  'bajo',
  'bateria',
  'güembe',
  'cajón',
  'chekere',
  'iyá',
  'itótele',
  'okónkolo',
  'batá',
  'camiseta',
  'short',
  'bermuda',
  'guayabera',
  'sombrero',
  'panama',
  'gorra',
  'visera',
  'lentes',
  'cadena',
  'anillo',
  'pulsera',
  'arete',
  'piercing',
  'tatuaje',
  'trenza',
  'moño',
  'afro',
  'rastas',
  'calvicie',
  'peluca',
  'extensiones',
  'uñas postizas',
  'gel',
  'laca',
  'crema',
  'perfume',
  'colonia',
  'desodorante',
  'jabon',
  'champú',
  'acondicionador',
  'cepillo',
  'peine',
  'secador',
  'plancha de pelo',
  'rulos',
  'bigudí',
  'celular',
  'movil',
  'telefono',
  'computadora',
  'laptop',
  'tablet',
  'television',
  'radio',
  'bocina',
  'audifonos',
  'ventilador',
  'aire acondicionado',
  'split',
  'nevera',
  'refrigerador',
  'freezer',
  'cocina',
  'horno',
  'microondas',
  'licuadora',
  'batidora',
  'cafetera',
  'olla de presion',
  'sarten',
  'caldero',
  'cuchillo',
  'tenedor',
  'cuchara',
  'plato',
  'vaso',
  'taza',
  'jarra',
];

// Función para obtener todas las palabras
export const getAllWords = () => [
  ...JERGA_CUBANA,
  ...INFLUENCERS_CUBANOS,
  ...COMIDA_CUBANA,
  ...LUGARES_CUBANOS,
  ...COSAS_CUBANAS,
];

// Función para obtener palabras por categoría
export const getWordsByCategory = (category: string) => {
  switch (category) {
    case 'jerga':
      return JERGA_CUBANA;
    case 'influencers':
      return INFLUENCERS_CUBANOS;
    case 'comida':
      return COMIDA_CUBANA;
    case 'lugares':
      return LUGARES_CUBANOS;
    case 'cosas':
      return COSAS_CUBANAS;
    default:
      return getAllWords();
  }
};

// Exportar WORDS para compatibilidad con el código existente
export const WORDS = getAllWords();
